import {
  CommercialSubType,
  Currency,
  IndustrialSubType,
  PropertyType,
  Purpose,
  ResidentialSubType,
} from "@/interface/property";
import { z } from "zod";

const amenitiesSchema = z.object({
  furnished: z.boolean(),
  parking: z.boolean(),
  gym: z.boolean(),
  swimmingPool: z.boolean(),
  internet: z.boolean(),
  balcony: z.boolean(),
  elevator: z.boolean(),
  wheelchair: z.boolean(),
  dishwasher: z.boolean(),
  petsAllowed: z.boolean(),
  smokingAllowed: z.boolean(),
  fireplace: z.boolean(),
  cableTv: z.boolean(),
  airConditioning: z.boolean(),
  heating: z.boolean(),
  securitySystem: z.boolean(),
  cctv: z.boolean(),
  churchNearby: z.boolean(),
  mosqueNearby: z.boolean(),
  security: z.boolean(),
  waterSupply: z.boolean(),
  electricity: z.boolean(),
});

export const propertySchema = z.object({
  title: z.string().min(1, "Title is required"),
  purpose: z.nativeEnum(Purpose),
  amenities: amenitiesSchema,
  slots: z.number().int().positive(),
  description: z.string().min(1, "Description is required"),
  bedrooms: z.number().int().nonnegative(),
  bathrooms: z.number().int().nonnegative(),
  address: z.string().min(1, "Address is required"),
  stateCapital: z.string().min(1, "State Capital is required"),
  size: z.number().positive(),
  toilets: z.number().int().nonnegative(),
  propertyType: z.nativeEnum(PropertyType),
  subType: z.union([
    z.nativeEnum(ResidentialSubType),
    z.nativeEnum(CommercialSubType),
    z.nativeEnum(IndustrialSubType),
  ]),
  images: z.array(z.instanceof(File)).min(1, "At least one image is required"),
  videoUrl: z.union([z.string().url().optional(), z.literal("")]).optional(),
  ownershipDocument: z
    .instanceof(File)
    .refine((file) => file.size > 0, "Ownership document is required"),
  price: z.number().positive(),
  currency: z.nativeEnum(Currency),
});

export type PropertyFormValues = z.infer<typeof propertySchema>;

export const defaultValues: PropertyFormValues = {
  title: "",
  purpose: Purpose.Rent,
  propertyType: PropertyType.RESIDENTIAL,
  subType: ResidentialSubType.BoysQuarters,
  price: 0,
  currency: Currency.NGN,
  bedrooms: 1,
  bathrooms: 1,
  toilets: 1,
  size: 0,
  slots: 1,
  address: "",
  stateCapital: "",
  description: "",
  videoUrl: "",
  amenities: {
    furnished: false,
    parking: false,
    gym: false,
    swimmingPool: false,
    internet: false,
    balcony: false,
    elevator: false,
    wheelchair: false,
    dishwasher: false,
    petsAllowed: false,
    smokingAllowed: false,
    fireplace: false,
    cableTv: false,
    airConditioning: false,
    heating: false,
    securitySystem: false,
    cctv: false,
    churchNearby: false,
    mosqueNearby: false,
    security: false,
    waterSupply: false,
    electricity: false,
  },
  images: [],
  ownershipDocument: new File([], ""),
};
